### PR TITLE
added loading bar

### PR DESCRIPTION
**Pull request by FireNdIce3**
I have added loading bar which will be visible when the api call is made and which will get hidden after we get the response from the api

### CODE REVIEW

**Comment by FireNdIce3** [comment]
I have also changed the colour of loading spinner when the dark mode is enabled

**Comment by Chirantanbanik** [comment]
Can you please share a gif or video of the changes you have made.

**Comment by FireNdIce3** [comment]
https://user-images.githubusercontent.com/99039829/193396236-45d68fd9-e6a0-4ff8-9f27-64d50bfc3b3c.mp4

**Comment by FireNdIce3** [comment]
Also can you please add hacktoberfest label in this?

**Comment by Chirantanbanik** [comment]
Good work✨

**Pull request merged**
